spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:devopsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    ai.devops: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
